### ISSUE TITLE
Add coveralls

### ISSUE THREAD

**Issue by Spectre5** [pronovic/apologies#27]
You might consider adding coveralls and then showing a badge with the coverage percentage in the README file.

On a side note, this project is a great learning tool and some people checking it out will not be very familiar with github.  You might add a section to the README (or ~CONTRIBUTING~ DEVELOPER guide) that talks about how the "behind the scenes" stuff gets setup on github.  As an example, if you add coveralls, then you'll need to add a secret, so you could provide a very short guide indicating that you need to add "this secret" to "here", then it becomes available in the github actions workflow as an environment variable, etc.  Any other web hooks or anything else in the "settings" page that another user cannot see is a good thing to document for newer users in a learning repository like this.  Maybe indicating how the documents get from here to readthedocs would be another good example.

**Comment by pronovic** [comment]
Thanks, good suggestion.   I remember looking at this briefly when I started working on apologies, but then it dropped off my radar.  Seems like I can use [coveralls-github-action](https://github.com/marketplace/actions/coveralls-github-action) from the GitHub marketplace.

Yes, you're right - the readthedocs integration is a good example of something that happens as a part of the build process, but isn't really visible to anyone except me.   That could use some extra documentation to explain how I set it up.
